baseurl: /blog

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true
  - scope:
      path: ""
    values:
      layout: "default"

# markdown highlight
markdown: kramdown
# highlighter: rouge

kramdown:
  # input: GFM
  syntax_highlighter: rouge
  # html_to_native: true

## Mathjax
mathjax:  true
mathjax_autoNumber: true

#
plugins:
  - jekyll-toc